# Generated by Django 3.2.8 on 2021-10-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prato', models.IntegerField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='prato',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prato',
            name='valor',
            field=models.FloatField(),
        ),
    ]
