# Generated by Django 3.2.8 on 2021-10-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211029_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
